[47기 김상원] ADD : Post Rooms
wecode-bootcamp-korea/47-2nd-IIIIEE-backend pull request #11
Opened 2023-07-19 16:40 UTC by Teachsue

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ㅇ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- room을 post하여, 맛집에 같이 갈 인원을 모집한다.
<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
구현하고자 하는 Room에 필요한 테이블들을 추가하였습니다.

<br />

## :: 테스트 결과 이미지
1. 방을 정상적으로 생성했을 때

![image](https://github.com/wecode-bootcamp-korea/47-2nd-IIIIEE-backend/assets/131442242/de3d4437-5656-492a-a9c7-d84e6e7aa69e)

2. 기존 같은 Host가 동일 시간, 같은 장소를 예약 할경우 불가하도록 예외처리.
![image](https://github.com/wecode-bootcamp-korea/47-2nd-IIIIEE-backend/assets/131442242/7e686146-b54b-4768-b4ac-3b4cf7e378ae)

<br />

## :: 기타 질문 및 특이 사항
- 저희 프로젝트의 메인 기능 중 하나인 Room 테이블 값이 확인이 필요한 사항이 많아 다소 딜레이 됐습니다.  깃 리베이스 작업 예정이며, 추가 구현 사항으로  이미지 업로드 구현까지 마무리 짓겠습니다. 감사합니다.

2023-07-20 06:13 UTC, Kang-kyunghun requested changes

2023-07-20 06:13 UTC, Kang-kyunghun commented on api/controllers/roomController.js
> +    }
globalErrorhandler를 적용한 것으로 아는데, 해당 코드가 적절 할까요?
확인해 주세요.

2023-07-20 06:13 UTC, Kang-kyunghun commented on api/models/roomDao.js
> +    try {
```suggestion
    try {
    const existingRoom = await dataSource.query(
        `SELECT 
        restaurant_id,
        host_id, 
        date, 
        time_id 
        FROM rooms 
        WHERE 
        restaurant_id = ? AND host_id = ? AND date = ? AND time_id = ?`,
        [restaurantId, hostId, date, timeId]
        );

    if (existingRoom.length > 0) {
        const error = new Error('EXISTED_DATA_INPUT');
        error.statusCode = 400;
        throw error;
    }

    
```

2023-07-20 06:13 UTC, Kang-kyunghun commented on api/models/roomDao.js
> +    postRooms,
```suggestion
  postRooms,
```

2023-07-20 06:13 UTC, Kang-kyunghun commented on api/services/roomService.js
> +    }
프리티어 설정 안 되어 있나요??
들여씌기나 형식이 뒤틀려 있는 것들이 많습니다

2023-07-20 06:13 UTC, Kang-kyunghun commented on db/migrations/20230718101417_create_users_table.sql
> +-- migrate:up
migration file들은 왜 올라 오는 거죠?
올라오면 안 될 것 같은데, 확인해 주세요.

2023-07-20 07:50 UTC, Teachsue commented on api/controllers/roomController.js
> +    }
깜빡하고 발견하지 못했습니다! 해결완료 했습니다 :) 감사합니다!

2023-07-21 02:22 UTC, Kang-kyunghun requested changes

2023-07-21 02:22 UTC, Kang-kyunghun commented on api/controllers/roomController.js
> +const postRooms = catchAsync(async (req, res) => {
```suggestion
const createRoom = catchAsync(async (req, res) => {
```

2023-07-21 02:22 UTC, Kang-kyunghun commented on api/models/roomDao.js
> +const postRooms = async (roomposts) => {
```suggestion
const createRoom = async (roomposts) => {
```

2023-07-21 02:22 UTC, Kang-kyunghun commented on api/models/roomDao.js
> +    [restaurantId, hostId, date, timeId]
해당 query는 따로 함수로 만들어 주세요.

2023-07-21 02:22 UTC, Kang-kyunghun commented on api/models/roomDao.js
> +  }
존재 여부를 파악하는 dao 함수를 가지고 해당 로직은 서비스에서 구현해 주세요.

2023-07-21 02:22 UTC, Kang-kyunghun commented on db/migrations/20230718101417_create_users_table.sql
> +CREATE TABLE users (
마이그레이션 파일 계속 올라옵니다.
안 올라오게 해주세요.

2023-07-21 03:56 UTC, Teachsue commented on db/migrations/20230718101417_create_users_table.sql
> +CREATE TABLE users (
확인하였습니다!

2023-07-24 06:26 UTC, merged