[47기 김상원] ADD : Upload Image
wecode-bootcamp-korea/47-2nd-IIIIEE-backend pull request #20
Opened 2023-07-23 14:18 UTC by Teachsue

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ㅇ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
방에서 대표하는 이미지를 추가하는 기능을 구현

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
Node에서 이미지를 업로드하는데 사용되는 multer를 사용하였으며, 아마존 S3 및 IAM, uuid를 활용하여 이미지 파일을 암호화하여 S3에 저장함.

<br />

## :: 테스트 결과 이미지
![image](https://github.com/wecode-bootcamp-korea/47-2nd-IIIIEE-backend/assets/131442242/fc5a6526-a735-4cbb-b3bc-dcd961d75c73)

<br />

## :: 기타 질문 및 특이 사항

기존 다른 수강생들과 진행하던 방식과 달리 Es6 방식으로 AWS를 활용하여야 할 때는, 자바스크립트 V3? 를 지원하는 @aws-sdk/client-s3 버전으로 사용을 하여야 한다는것을 알게 되었습니다.
시간이 상당히 오래 걸린만큼 이미지 업로드에 성공하였을 때 굉장히 행복했습니다...!
 비록 트랜잭션은 이전 기수분들 참고와 gpt를 활용하였으나, 새로운 기능을 구현해보았다는 것에 코딩에 조금이나마 자신감이 생겼습니다...
 항상 감사합니다 n(__)n

2023-07-26 01:22 UTC, Kang-kyunghun requested changes

2023-07-26 01:22 UTC, Kang-kyunghun commented on api/models/roomDao.js
> +  const queryRunner = dataSource.createQueryRunner();
해당 코드에서는 서로 다른 테이블에 대한 수정 사항이 없기 때문에 따로 transaction을 사용할 필요는 없을 것 같습니다.
제거해 주세요.

2023-07-26 01:22 UTC, Kang-kyunghun commented on api/routes/roomRouter.js
> +  '/roomImage',
```suggestion
  '/image',
```

2023-07-26 01:26 UTC, Teachsue commented on api/models/roomDao.js
> +  const queryRunner = dataSource.createQueryRunner();
옙! 확인하였습니다!

2023-07-27 12:21 UTC, Teachsue commented
최종 검토 및 에러핸들링을 마친 커밋 입니다.
다소 혼잡스러운 점 죄송합니다.

2023-07-31 09:50 UTC, merged