Features/filtering restaurant
wecode-bootcamp-korea/47-2nd-IIIIEE-backend pull request #3
Opened 2023-07-18 04:54 UTC by jseongnam

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [O] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
restaurant을 filtering을 통해 원하는 식당만 데이터 전송

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
127.0.0.1:3000/filter?type=일식&district_id=4

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
![image](https://github.com/wecode-bootcamp-korea/47-2nd-IIIIEE-backend/assets/105405028/f9a8bc56-802c-4fc5-9840-33290febb99d)
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
![image](https://github.com/wecode-bootcamp-korea/47-2nd-IIIIEE-backend/assets/105405028/6b133784-95d1-4f63-b542-87605d5dcc34)

3. 작성한 Test Code가 잘 통과했는지 확인할 수 있는 이미지
![image](https://github.com/wecode-bootcamp-korea/47-2nd-IIIIEE-backend/assets/105405028/6f44b5ef-4b23-4ae6-808b-028e953ea175)

<br />

## :: 기타 질문 및 특이 사항
Dao에서 더 효과적인 방법이 있을것이라 생각이 됩니다. 그게 어떤걸지 궁금합니다.
git rebase로 전에 작업을 삭제하자, 오류가 발생합니다. 이것의 해결방법도 궁금합니다.

2023-07-19 01:43 UTC, Kang-kyunghun requested changes

2023-07-19 01:43 UTC, Kang-kyunghun commented on api/controllers/filterController.js
> +import {filterService} from "../services/index.js";
```suggestion
import { restaurantService } from "../services/index.js";
```

2023-07-19 01:43 UTC, Kang-kyunghun commented on api/controllers/filterController.js
> +const filterController = async(req,res) => {
```suggestion
const restaurantController = async(req, res) => {
```

2023-07-19 01:43 UTC, Kang-kyunghun commented on api/controllers/filterController.js
> +    const values = Object.values(req.query);
key와 value를 왜 나누시나요?
그렇게 되면 key와 value 사이에 관계가 끊기게 되지 않을까요?

2023-07-19 01:43 UTC, Kang-kyunghun commented on api/controllers/filterController.js
> +    const filteringData = await filterService.filterService(keys,values);
```suggestion
    const restaurants = await filterService.filterService(keys,values);
```

2023-07-19 01:43 UTC, Kang-kyunghun commented on .gitignore
> +>>>>>>> 8d44a3cd (INITIAL-SETTING)
conflict 해결이 잘 안 된 곳들이 있습니다. 코드 전체적으로 확인해 주세요.

2023-07-19 01:43 UTC, Kang-kyunghun commented on api/controllers/index.js
> +}
```suggestion
import {roomData} from "./roomController.js";

export {
    roomData    
}
```

2023-07-19 01:43 UTC, Kang-kyunghun commented on api/controllers/roomController.js
> +import {queryByAsync} from "../services/index.js";
queryByAsync 라는 함수명은 뭘까요?
controller 함수명은 잘 바꾸었습니다. 그에 맞게 service, dao도 수정해 주시면 좋을 것 같습니다.

그리고 리나님도 room쪽 하시는 것 같던데, 파일명 통일 시킬 수 있게 논의해 주세요.
```suggestion
import { queryByAsync } from "../services/index.js";
```

2023-07-19 01:43 UTC, Kang-kyunghun commented on api/controllers/roomController.js
> +    }
2차 프로젝트는 전체 error handler 적용해 주세요.
해당 사항은 혼자서 진행하면 안 되고 팀원들과 상의해 주세요.

2023-07-19 01:43 UTC, Kang-kyunghun commented on api/models/roomDao.js
> +const getRes = async(conditionQuery) => {
```suggestion
const getRoomList = async(conditionQuery) => {
```

2023-07-19 01:43 UTC, Kang-kyunghun commented on api/models/roomDao.js
> +    const queryRunner = await dataSource.createQueryRunner();
Transaction을 사용한 이유를 코멘트로 남겨주세요.

2023-07-19 01:43 UTC, Kang-kyunghun commented on api/models/roomDao.js
> +                WHERE ${totalConditionQuery}
where 절은 잘 만들었습니다.

보통 목록을 조회하는 query는 조건뿐만 아니라, 정렬과 limit&offset도 필수로 주어야 합니다.
만약 상의된 값이 없다고 한다면 default 값이 들어올 수 있도록 진행하셔야 합니다.

2023-07-19 05:47 UTC, jseongnam commented
피드백 적용했습니다. 프론트와 맞춰봤습니다.

2023-07-19 10:51 UTC, kyeongraekim requested changes

2023-07-19 10:51 UTC, kyeongraekim commented on api/controllers/roomCheckController.js
> +export{roomCheckData}
- import 문 배구 구조 분해 할당을 표현하는 내용에 1번라인은 내부 whitespace 가 없고, 2번 라인에는 있네요. 가독성을 위하여 2번 포맷으로 통일시켜주세요!
- 그리고 2번 라인과 3번 라인에 라인브레이킹을 꼭 해주셔서 실제 진행하는 코드와 임포트 문의 영역구분을 명시해주세요!

2023-07-19 10:51 UTC, kyeongraekim commented on api/models/index.js
> +
- 불필요한 공백을 제거해주세요.

2023-07-19 10:51 UTC, kyeongraekim commented on api/routes/roomCheckRouter.js
> +const roomCheckRouter = express.Router();
- 이곳도 임포트 문과 다른 코드 진행의 영역구분을 위해 라인 브레이킹을 하여주세요!

2023-07-19 10:51 UTC, kyeongraekim commented on db/migrations/20230718101511_create.sql
> +CREATE TABLE users (
-필터링에 user 테이블 생성 마이그레이션이 함께 올라오게 된 것은 혹시 의도한 내용이실까요?

2023-07-19 10:51 UTC, kyeongraekim commented on api/models/roomCheckDao.js
> +            let district_id = await queryRunner.query(
- camelCase로 변경해서 변수명을 설정해주세요!

2023-07-19 10:51 UTC, kyeongraekim commented on api/models/roomCheckDao.js
> +        let roomsTransform = [];
- 해당 내용 처럼 초기값을 선언하는 것은 C언어 계열에 보다 적합한 방법이고, 자바/타입스크립트, 파이썬 등의 실무 웹 개발 환경에서 활용하기에는 부적절 해 보입니다. 참고해주세요!

2023-07-19 10:55 UTC, jseongnam commented on api/models/index.js
> +
수정했습니다!

2023-07-19 10:55 UTC, jseongnam commented on api/routes/roomCheckRouter.js
> +const roomCheckRouter = express.Router();
수정했습니다

2023-07-19 10:59 UTC, jseongnam commented on api/models/roomCheckDao.js
> +            let district_id = await queryRunner.query(
수정했습니다

2023-07-20 01:10 UTC, Kang-kyunghun commented
리뷰 남긴거에 대한 코멘트를 잘 안 읽으시는 것 같네요..
해당 PR은 따로 만나서 보겠습니다.

2023-07-21 02:14 UTC, Kang-kyunghun requested changes

2023-07-21 02:14 UTC, Kang-kyunghun commented on api/models/restaurantDao.js
> +      Date,
Date는 JS이미 지정된 class가 있을겁니다. 따라서 다음과 같이 변경해 주세요.
```suggestion
      date,
```

2023-07-21 02:14 UTC, Kang-kyunghun commented on api/models/restaurantDao.js
> +    if (Date) {
```suggestion
    if (date) {
```

2023-07-21 08:12 UTC, merged