[47기 신동현] Add : 식당 정보 조회 기능
wecode-bootcamp-korea/47-2nd-IIIIEE-backend pull request #8
Opened 2023-07-19 08:13 UTC by donghyeun02

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 식당 id값을 받아와 해당 식당에 대한 정보(이름, 지역, ...)을 조회하는 기능 구현

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 식당 id값을 params로 가져옴 -> 없을 시 키에러 처리

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
<img width="718" alt="스크린샷 2023-07-19 오후 5 10 43" src="https://github.com/wecode-bootcamp-korea/47-2nd-IIIIEE-backend/assets/129716523/986a5210-07ea-482a-bc32-8ed80c80feba">

3. 작성한 Test Code가 잘 통과했는지 확인할 수 있는 이미지
4. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2023-07-19 08:46 UTC, bigfanoftim requested changes
<img width="347" alt="image" src="https://github.com/wecode-bootcamp-korea/47-2nd-IIIIEE-backend/assets/62135254/7e1e5a53-f7ff-42b7-bcec-b0fcc7ad79b5">
migration이 전부 지워졌습니다 ㅠ_ㅠ 확인해주세요!

2023-07-19 09:31 UTC, donghyeun02 commented
db migration은 DB 수정할 게 많아서 싹 다 지우고 새로 만들었습니다...

2023-07-20 01:06 UTC, Kang-kyunghun requested changes

2023-07-20 01:06 UTC, Kang-kyunghun commented on api/services/restaurantService.js
> +  return await restaurantDao.getRestaurantInfo(restaurantId);
```suggestion
const getRestaurantInfo = async (restaurantId) => {
  return await restaurantDao.getRestaurantInfo(restaurantId);
```
```suggestion
const getRestaurantInfo = async (restaurantId) => {
  //restaurant 정보가 없을 경우에 대한 404 에러 추가
  return await restaurantDao.getRestaurantInfo(restaurantId);
```

2023-07-21 02:16 UTC, Kang-kyunghun requested changes

2023-07-21 02:16 UTC, Kang-kyunghun commented on api/services/restaurantService.js
> +  return await restaurantDao.getRestaurantInfo(restaurantId);
exist를 따로 만들 필요는 없을 것 같습니다.

```suggestion
const getRestaurantInfo = async (restaurantId) => {
  const restaurant = await restaurantDao.getRestaurantInfo(restaurantId);

  if (!restaurant) {
    const error = new Error('INVALID_RESTAURANT_ID');
    error.statusCode = 404;

    throw error;
  }

  return restaurant
```

2023-07-21 06:30 UTC, merged